"use client";

import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";

import { Card } from "@/components/ui/card";
import { MagneticHeading } from "@/components/MagneticHeading";
import { TiltCard } from "@/components/TiltCard";

const projects = [
  {
    id: 10,
    title: "PickupAI",
    year: "2026",
    link: "https://www.listedpei.ca/pickupai",
    tag: "AI Tool",
    description: "Free Google Business Profile kits for PEI small businesses, generated by AI. Helps local owners get found on Google faster with zero technical know-how required.",
    tech: ["Next.js", "AI", "Local SEO"],
    color: "#7C3AED",
    featured: true,
  },
  {
    id: 11,
    title: "Lustrouz Aesthetics",
    year: "2026",
    link: "https://lustrouz-web.vercel.app/",
    tag: "Medical Skincare",
    description: "Premium website for a Toronto medical skincare clinic. Science-backed positioning, luxury aesthetic, and a conversion-focused layout built to attract high-intent clients.",
    tech: ["Next.js", "Tailwind CSS", "UX/UI"],
    color: "#DB2777",
    featured: true,
  },
  {
    id: 0,
    title: "Cricket PEI",
    year: "2026",
    link: "https://cricketpei.ca",
    tag: "Sports Federation",
    description: "Official site for PEI Cricket. Built for speed and easy access to match data and federation updates.",
    tech: ["HTML5", "Tailwind CSS", "UI Design"],
    color: "#0071e3",
    image: "/assets/projects/cricket.jpg"
  },
  {
    id: 1,
    title: "Fat Cat Bakery",
    year: "2026",
    link: "https://fatcatbakery.netlify.app/",
    tag: "Local Business",
    description: "Polished bakery site with a focus on simple navigation and conversion-friendly layouts.",
    tech: ["Next.js", "Tailwind CSS", "UX/UI"],
    color: "#F2CC8F",
    image: "/assets/projects/fatcat.jpg"
  },
 
  {
    id: 2,
    title: "Red Soil",
    year: "2026",
    link: "https://redsoil.netlify.app/",
    tag: "Community Branding",
    description: "A clean, structured brand site inspired by PEI's identity. Focus on grid systems and solid spacing.",
    tech: ["HTML5", "Tailwind CSS", "Brand UI"],
    color: "#BC4749",
    image: "/assets/projects/redsoil.jpg"
  },
  {
    id: 3,
    title: "Lootbins Canada",
    year: "2026",
    link: "https://www.lootbinscanada.com/",
    tag: "E-commerce & Retail",
    description: "Inventory-focused retail site. Clean layout designed to handle high product volume and clear navigation.",
    tech: ["Shopify", "UI Design", "E-commerce"],
    color: "#E63946",
    image: "/assets/projects/lootbins.jpg"
  },
  {
    id: 4,
    title: "Listed PEI",
    year: "2026",
    link: "https://listedpei.ca",
    tag: "Directory Platform",
    description: "A comprehensive business directory for Prince Edward Island. Connects local businesses with customers through an intuitive search and listing experience.",
    tech: ["Next.js", "PostgreSQL", "Full Stack"],
    color: "#059669",
  }
];

const cardVariants = {
  hidden: { opacity: 0, y: 32 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, delay: i * 0.12, ease: [0.25, 0.46, 0.45, 0.94] }
  })
};

export function PortfolioSection({ showTitle = true }: { showTitle?: boolean }) {
  return (
    <section id="portfolio" className="relative overflow-hidden py-14 sm:py-20 md:py-28">
      <div className="mx-auto w-[min(1100px,calc(100%-1rem))] sm:w-[min(1100px,calc(100%-2rem))]">
        {showTitle && (
          <MagneticHeading
            title="Work that speaks for itself"
            subtitle="Websites, AI tools, and digital marketing. Real projects for real businesses, built to perform."
          />
        )}

        {/* Featured projects */}
        <div className="mt-8 grid gap-4 sm:mt-10 sm:gap-5 md:grid-cols-2">
          {projects.filter((p) => p.featured).map((project, i) => (
            <motion.div
              key={project.id}
              custom={i}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-60px" }}
              variants={cardVariants}
            >
              <a
                href={project.link}
                target="_blank"
                rel="noopener noreferrer"
                className="group block h-full"
              >
                <TiltCard className="h-full" tiltAmount={8} scale={1.01}>
                  <Card
                    className="flex h-full flex-col p-5 sm:p-6 transition-colors bg-card"
                    style={{ borderColor: `${project.color}40` }}
                  >
                    <div className="flex items-start justify-between gap-3 mb-3">
                      <div className="flex items-center gap-2">
                        <span
                          className="inline-block rounded-full px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wider sm:text-xs whitespace-nowrap"
                          style={{ backgroundColor: `${project.color}15`, color: project.color }}
                        >
                          {project.tag}
                        </span>
                        <span
                          className="inline-block rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider sm:text-xs"
                          style={{ backgroundColor: `${project.color}20`, color: project.color }}
                        >
                          Featured
                        </span>
                      </div>
                      <span className="text-xs text-muted-foreground shrink-0">{project.year}</span>
                    </div>

                    <h3 className="flex items-center gap-2 font-heading text-lg font-semibold sm:text-xl">
                      {project.title}
                      <ArrowUpRight className="size-4 text-muted-foreground opacity-0 transition-all group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:opacity-100 shrink-0" />
                    </h3>

                    <p className="mt-3 text-sm leading-relaxed text-muted-foreground flex-1">
                      {project.description}
                    </p>

                    <div className="mt-4 flex flex-wrap gap-2 pt-1">
                      {project.tech.map((t) => (
                        <span
                          key={t}
                          className="rounded-md px-2.5 py-1 text-[10px] font-medium sm:text-xs"
                          style={{ backgroundColor: `${project.color}12`, color: project.color, border: `1px solid ${project.color}30` }}
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  </Card>
                </TiltCard>
              </a>
            </motion.div>
          ))}
        </div>

        {/* Regular projects */}
        <div className="mt-4 sm:mt-5 grid gap-4 sm:gap-5 md:grid-cols-2 lg:grid-cols-3">
          {projects.filter((p) => !p.featured).map((project, i) => (
            <motion.div
              key={project.id}
              custom={i}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-60px" }}
              variants={cardVariants}
            >
              <a
                href={project.link}
                target="_blank"
                rel="noopener noreferrer"
                className="group block h-full"
              >
                <TiltCard className="h-full" tiltAmount={8} scale={1.01}>
                  <Card className="flex h-full flex-col p-5 sm:p-6 transition-colors hover:border-primary/30 bg-card">
                  <div className="flex items-start justify-between gap-3 mb-3">
                    <span
                      className="inline-block rounded-full px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wider sm:text-xs whitespace-nowrap"
                      style={{
                        backgroundColor: `${project.color}15`,
                        color: project.color
                      }}
                    >
                      {project.tag}
                    </span>
                    <span className="text-xs text-muted-foreground shrink-0">{project.year}</span>
                  </div>

                  <h3 className="flex items-center gap-2 font-heading text-lg font-semibold sm:text-xl">
                    {project.title}
                    <ArrowUpRight className="size-4 text-muted-foreground opacity-0 transition-all group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:opacity-100 shrink-0" />
                  </h3>

                  <p className="mt-3 text-sm leading-relaxed text-muted-foreground flex-1">
                    {project.description}
                  </p>

                  <div className="mt-4 flex flex-wrap gap-2 pt-1">
                    {project.tech.map((t) => (
                      <span
                        key={t}
                        className="rounded-md px-2.5 py-1 text-[10px] font-medium sm:text-xs"
                        style={{ backgroundColor: `${project.color}12`, color: project.color, border: `1px solid ${project.color}30` }}
                      >
                        {t}
                      </span>
                    ))}
                  </div>
                  </Card>
                </TiltCard>
              </a>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
